[package]
name = "audio_controller_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.1"
rodio = "0.19.0"
tokio = {version = "1.39.2", features = ["full"]}
warp = "0.3.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"